apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.image.port }}
