replicaCount: 1

image:
  repository: tavrds/interior-design-studio
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  DEBUG: "True"
  SECRET_KEY: "supersecretkey"
  ALLOWED_HOSTS: "tavrds-7177.uksouth.cloudapp.azure.com"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "3CUD9iCyMT"
  POSTGRES_HOST: "postgres-postgresql.default.svc.cluster.local"
  POSTGRES_PORT: "5432"
  DJANGO_ALLOWED_HOSTS: "tavrds-7177.uksouth.cloudapp.azure.com"


ingress:
  enabled: true
  className: "nginx"
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # acme.cert-manager.io/http01-edit-in-place: "true"
  # extraPaths:
  # - path: /.well-known/acme-challenge/*
  #   pathType: ImplementationSpecific
  #   backend:
  #     service:
  #       name: ingress-nginx-controller
  #       port:
  #         number: 80
  hosts:
    - host: tavrds-7177.uksouth.cloudapp.azure.com
      paths:
        - path: /django
          pathType: Prefix
  tls: []
    # - hosts:
    #     - ttavrds-7177.uksouth.cloudapp.azure.com
    #   secretName: tls-secret
