replicaCount: 1

image:
  repository: tavrds/interior-design-studio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  DEBUG: "True"
  SECRET_KEY: "supersecretkey"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "interior_db"
  POSTGRES_USER: "interior_user"
  POSTGRES_PASSWORD: "interior_pass"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: tavrds.uksouth.cloudapp.azure.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
