replicaCount: 1

image:
  repository: tavrds/interior-design-django
  tag: 1.0.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  DEBUG: "True"
  SECRET_KEY: "supersecretkey"
  # ALLOWED_HOSTS: "*"
  POSTGRES_DB: "designStudioDB"
  POSTGRES_USER: "designStudio"
  POSTGRES_PASSWORD: "eyciqj9ipyjs7"
  POSTGRES_HOST: "custom-postgres.default.svc.cluster.local"
  POSTGRES_PORT: "5432"
  FORCE_SCRIPT_NAME: "/django"
  DJANGO_ALLOWED_HOSTS: "*"
  CSRF_TRUSTED_ORIGINS: "https://tavrds-7177.uksouth.cloudapp.azure.com"


ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

  hosts:
    - host: tavrds-7177.uksouth.cloudapp.azure.com
      paths:
        - path: /django(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - tavrds-7177.uksouth.cloudapp.azure.com
      secretName: tls-frontend
