apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    app: {{ include "django-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "django-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "django-app.name" . }}
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          # envFrom:
          #   - secretRef:
          #       name: postgres-postgresql
          env:
            - name: DEBUG
              value: {{ .Values.env.DEBUG | quote }}
            - name: SECRET_KEY
              value: {{ .Values.env.SECRET_KEY | quote }}
            # - name: ALLOWED_HOSTS
            #   value: {{ .Values.env.DJANGO_ALLOWED_HOSTS | quote }}
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ .Values.env.DJANGO_ALLOWED_HOSTS | quote }}
            - name: FORCE_SCRIPT_NAME
              value: {{ .Values.env.FORCE_SCRIPT_NAME | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.env.POSTGRES_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.env.POSTGRES_PORT | quote }}
            - name: CSRF_TRUSTED_ORIGINS
              value: {{ .Values.env.CSRF_TRUSTED_ORIGINS | quote }}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 6
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 6