apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    app: {{ include "django-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "django-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "django-app.name" . }}
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: {{ .Values.env.DEBUG | quote }}
            - name: SECRET_KEY
              value: {{ .Values.env.SECRET_KEY | quote }}

            - name: ALLOWED_HOSTS
              value: {{ .Values.env.ALLOWED_HOSTS | quote }}

            - name: FORCE_SCRIPT_NAME
              value: {{ .Values.env.FORCE_SCRIPT_NAME | quote }}

            - name: STATIC_URL
              value: {{ .Values.env.STATIC_URL | quote }}

            - name: CSRF_TRUSTED_ORIGINS
              value: {{ .Values.env.CSRF_TRUSTED_ORIGINS | quote }}

            - name: CORS_ALLOWED_ORIGINS
              value: {{ .Values.env.CORS_ALLOWED_ORIGINS | quote }}

            - name: CORS_ALLOW_CREDENTIALS
              value: {{ .Values.env.CORS_ALLOW_CREDENTIALS | quote }}

            - name: HTTPS
              value: {{ .Values.env.HTTPS | quote }}

            - name: SECURE_HSTS_SECONDS
              value: {{ .Values.env.SECURE_HSTS_SECONDS | quote }}

            - name: USE_X_FORWARDED_HOST
              value: {{ .Values.env.USE_X_FORWARDED_HOST | quote }}

            - name: EMAIL_HOST_USER
              value: {{ .Values.env.EMAIL_HOST_USER | quote }}
            - name: EMAIL_HOST_PASSWORD
              value: {{ .Values.env.EMAIL_HOST_PASSWORD | quote }}
            - name: EMAIL_HOST
              value: {{ .Values.env.EMAIL_HOST | quote }}
            - name: EMAIL_PORT
              value: {{ .Values.env.EMAIL_PORT | quote }}
            - name: ADMIN_NOTIFICATION_EMAIL
              value: {{ .Values.env.ADMIN_NOTIFICATION_EMAIL | quote }}

            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.env.POSTGRES_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.env.POSTGRES_PORT | quote }}
            - name: PGDATA
              value: {{ .Values.env.PGDATA | quote }}

            - name: CELERY_BROKER_URL
              value: {{ .Values.env.CELERY_BROKER_URL | quote }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.env.CELERY_RESULT_BACKEND | quote }}


