apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    app: {{ include "django-app.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 8000
  selector:
    app: {{ include "django-app.name" . }}



# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "django-app.fullname" . }}
#   labels:
#     app: {{ include "django-app.name" . }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: 8000
#   loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
#   selector:
#     app: {{ include "django-app.name" . }}